@startuml
start

:Passo 1: Acessar a página de formulário;
:1.1 Clicar no botão "Envie seu projeto";
:1.2 Ser redirecionado para a página de formulário;

:Passo 2: Preencher "Informações da Empresa";
:2.1 Inserir Nome da Empresa;
:2.2 Inserir CNPJ;
:2.3 Inserir Email para contato;
:2.4 Selecionar número de colaboradores;
:2.4.1 Escolher uma das opções;
:2.5 Informar se a empresa está vinculada ao Hubs;
:2.6 Inserir Área de atuação;

:Passo 3: Preencher "Informações do Projeto";
:3.1 Informar prazo do projeto;
:3.2 Inserir tipo de demanda;
:3.3 Preencher descrição do projeto;

:Passo 4: Aceitar os termos de uso;
:4.1 Clicar na caixa de seleção;
:4.2 (Opcional) Clicar no link para ler os termos;

:Passo 5: Enviar o formulário;
:5.1 Clicar no botão "Enviar";

stop
@enduml